# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'basicnative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for basicnative

  react_native_path = "../node_modules/react-native"
  pod "React", :path => "../node_modules/react-native"
  pod "yoga", :path => "#{react_native_path}/ReactCommon/yoga/yoga.podspec"
  pod 'Taplytics'

end
